DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(100), NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

//se crean tres odontologos para probar con los test
INSERT INTO ODONTOLOGOS (NOMBRE, APELLIDO, MATRICULA) VALUES ('Santiago', 'Hernandez', 1234), ('Peter', 'Hernandez', 1245), ( 'Lucia', 'Murga', 1111);


drop table IF EXISTS DOMICILIOS;
create TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(100) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(100) NOT NULL, PROVINCIA VARCHAR(100) NOT NULL);

drop table IF EXISTS PACIENTES;
create TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA DATE NOT NULL, DOMICILIO_ID INT);

-- para test --
INSERT INTO DOMICILIOS(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Robbinson', 1335, 'Cerrito', 'Montevideo'), ('Guaviyu', 1369, 'Brazo Oriental', 'Montevideo');

INSERT INTO PACIENTES(NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Pablo', 'Garcia', '11234562', '2023-01-01', 1);
INSERT INTO PACIENTES(NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Gustavo', 'Rodriguez', '25645912', '2023-02-01', 2);
